"""
ACCOUNT TYPE
"""
ACCOUNT_TESTING = "Testing"
ACCOUNT_STANDARD = "Standard"
ACCOUNT_PROFESSIONAL = "Professional"
ACCOUNT_BUSINESS = "Business"

"""
    PRICING
"""
# TESTING
ACCOUNT_TESTING_FORMS = 20
ACCOUNT_TESTING_WORKSPACES = 5
ACCOUNT_TESTING_SUBMISSIONS = 50
ACCOUNT_TESTING_STORAGE = 100  # MB

# STANDARD
ACCOUNT_STANDARD_FORMS = 5
ACCOUNT_STANDARD_WORKSPACES = 3
ACCOUNT_STANDARD_SUBMISSIONS = 1500
ACCOUNT_STANDARD_STORAGE = 10000

# PROFESSIONAL
ACCOUNT_PROFESSIONAL_FORMS = 20
ACCOUNT_PROFESSIONAL_WORKSPACES = 10
ACCOUNT_PROFESSIONAL_SUBMISSIONS = 3000
ACCOUNT_PROFESSIONAL_STORAGE = 30000

# BUSINESS
ACCOUNT_BUSINESS_FORMS = float('inf')
ACCOUNT_BUSINESS_WORKSPACES = 100
ACCOUNT_BUSINESS_SUBMISSIONS = 100000
ACCOUNT_BUSINESS_STORAGE = 100000


# LIMITATIONS
ACCOUNT_LIMITATIONS = {
    ACCOUNT_TESTING: {
        "total_forms": ACCOUNT_TESTING_FORMS,
        "total_workspaces": ACCOUNT_TESTING_WORKSPACES,
        "total_submissions": ACCOUNT_TESTING_SUBMISSIONS,
        "total_storage": ACCOUNT_TESTING_STORAGE
    },
    ACCOUNT_STANDARD: {
        "total_forms": ACCOUNT_STANDARD_FORMS,
        "total_workspaces": ACCOUNT_STANDARD_WORKSPACES,
        "total_submissions": ACCOUNT_STANDARD_SUBMISSIONS,
        "total_storage": ACCOUNT_STANDARD_STORAGE
    },
    ACCOUNT_PROFESSIONAL: {
        "total_forms": ACCOUNT_PROFESSIONAL_FORMS,
        "total_workspaces": ACCOUNT_PROFESSIONAL_WORKSPACES,
        "total_submissions": ACCOUNT_PROFESSIONAL_SUBMISSIONS,
        "total_storage": ACCOUNT_PROFESSIONAL_STORAGE
    },
    ACCOUNT_BUSINESS: {
        "total_forms": ACCOUNT_BUSINESS_FORMS,
        "total_workspaces": ACCOUNT_BUSINESS_WORKSPACES,
        "total_submissions": ACCOUNT_BUSINESS_SUBMISSIONS,
        "total_storage": ACCOUNT_BUSINESS_STORAGE
    },
}
