# Generated by Django 4.0 on 2021-12-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
