# Generated by Django 4.0 on 2021-12-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_form_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='alerts',
            field=models.BooleanField(default=False),
        ),
    ]
