# Generated by Django 4.0 on 2021-12-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_form_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
