# Generated by Django 4.0 on 2022-01-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submissionfileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfileupload',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
