# Generated by Django 4.0 on 2022-01-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_alter_submissionfileupload_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfileupload',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submission.submission'),
        ),
    ]
