# Generated by Django 4.0 on 2022-01-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_verified_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard'), ('PROFESSIONAL', 'Professional'), ('BUSINESS', 'Business')], default='FREE', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='paid_user',
            field=models.BooleanField(default=False),
        ),
    ]
