# Generated by Django 4.0 on 2022-01-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_account_type_user_paid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Standard', 'Standard'), ('Professional', 'Professional'), ('Business', 'Business')], default='Free', max_length=255),
        ),
    ]
