# Generated by Django 4.0 on 2022-01-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Free', (('Forms', '100'), ('Workspace', '100'), ('Submission', '100'))), ('Standard', (('Forms', '100'), ('Workspace', '100'), ('Submission', '100'))), ('Professional', (('Forms', '100'), ('Workspace', '100'), ('Submission', '100'))), ('Business', (('Forms', '100'), ('Workspace', '100'), ('Submission', '100')))], default='Free', max_length=255),
        ),
    ]
