# Generated by Django 4.0 on 2022-01-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Testing', 'Testing'), ('Standard', 'Standard'), ('Professional', 'Professional'), ('Business', 'Business')], default='Testing', max_length=255),
        ),
    ]
