name: Dropform Backend Unit Test Pipeline

on: [push,pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9.13
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: python manage.py migrate
    - name: Run Check Deploy
      run: python manage.py  check --deploy
    - name: Run tests
      run: python -W ignore::RuntimeWarning  manage.py test
